name: batdata
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.7.*
  - pandas==1.*
  - scipy==1.3.*
  - pytables
  - pydantic
  - xlrd
  - h5py
  - jupyterlab
  - matplotlib
  - flake8
  - pytest
  - tqdm
  - pip
  - pip:
    - git+https://github.com/materials-data-facility/MaterialsIO.git
    - -e .  # Installs the batdata library in development mode
